-d C:\LinuxWorkSpace\gowin-fpga-projects-repository\Gowin_Tang_Primer_20K_DDR3_AXI_Stream_FIFO_Warpper\impl\gwsynthesis\Gowin_Tang_Primer_20K_DDR3_AXI_Stream_FIFO_Warpper.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\LinuxWorkSpace\gowin-fpga-projects-repository\Gowin_Tang_Primer_20K_DDR3_AXI_Stream_FIFO_Warpper\src\Gowin_Tang_Primer_20K_DDR3_AXI_Stream_FIFO_Warpper.cst
-cfg C:\LinuxWorkSpace\gowin-fpga-projects-repository\Gowin_Tang_Primer_20K_DDR3_AXI_Stream_FIFO_Warpper\impl\pnr\device.cfg
-sdc C:\LinuxWorkSpace\gowin-fpga-projects-repository\Gowin_Tang_Primer_20K_DDR3_AXI_Stream_FIFO_Warpper\src\Gowin_Tang_Primer_20K_DDR3_AXI_Stream_FIFO_Warpper.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
